#!/usr/bin/env escript

run_tests([]) ->
    ok;
run_tests([Test|Modules]) ->
    case code:load_file(list_to_atom(Test)) of
	{module, Module} -> Module:test();
	{error, Reason} -> io:format("error loading ~p ~p~n", [Test, Reason])
    end,
    run_tests(Modules).

cleanup([]) ->
    ok;
cleanup([_Test|Modules]) ->
    cleanup(Modules).

main(Tests) ->
    run_tests(Tests),
    cleanup(Tests);
main(_) ->
    halt(1).